#pragma once

// containers
#include <array>
#include <deque>
#include <forward_list>
#include <list>
#include <map>
#include <queue>
#include <set>
#include <span>
#include <stack>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>

// misc
#include <cassert>
#include <chrono>
#include <compare>
#include <concepts>
#include <expected>
#include <filesystem>
#include <format>
#include <functional>
#include <future>
#include <iterator>
#include <memory>
#include <optional>
#include <ranges>
#include <source_location>
#include <stdexcept>
#include <thread>
#include <tuple>
#include <type_traits>
#include <utility>
#include <variant>

// thirdparty
#include <boost/asio.hpp>
#include <boost/asio/experimental/awaitable_operators.hpp>
#include <boost/asio/experimental/coro.hpp>
#include <boost/asio/experimental/co_composed.hpp>
#include <boost/beast/core.hpp>
#include <boost/beast/http.hpp>
#include <boost/beast/ssl.hpp>
#include <boost/json.hpp>
#include <boost/mysql.hpp>
#include <boost/signals2.hpp>
#include <boost/utility/base_from_member.hpp>
#include <fmt/ostream.h>
#include <spdlog/spdlog.h>
#include <tl/optional.hpp>
